volumes:
  postgres:
services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    ports:
      - "2333:2333"
    volumes:
      - "./config/lavalink/application.yml:/opt/Lavalink/application.yml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18080:8080
