# https://taskfile.dev

version: '3'


vars:
  APP_NAME: yuri
  CONFIG_DIR: ./config/private.config.toml
  BIN_DIR: ./bin
  BIN: '{{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}}'


tasks:

  default:
    deps:
      - release

  release:
    deps:
      - build

  build:
    deps:
      - embedfe
    cmds:
      - task: builddry

  builddry:
    cmds:
      - go build
          -v
          -o {{.BIN}}
            ./cmd/{{.APP_NAME}}/main.go

  run:
    deps:
      - builddry
    cmds:
      - '{{.BIN}}
          -c {{.CONFIG_DIR}}
          -l 5
          -debug'

  deps:
    dir: web/
    sources:
      - "package.json"
      - "yarn.lock"
    generates:
      - "node_modules/**"
    cmds:
      - "yarn"

  buildfe:
    dir: web/
    sources:
      - "**"
    generates:
      - "dist/**"
    deps:
      - deps
    cmds:
      - yarn build

  embedfe:
    deps:
      - buildfe
    cmds:
      - '{{if eq OS "windows"}}
          xcopy web\\dist pkg\\webserver\\_webdist /E /H /Y
        {{else}}
          cp -r web/dist/* pkg/webserver/_webdist
        {{end}}'

  runfe:
    dir: web/
    deps:
      - deps
    cmds:
      - yarn run dev

  docker:
    cmds:
      - 'docker-compose
          -f ./docker-compose.dev.yml
          {{.CLI_ARGS}}'

  init:
    preconditions:
      - sh: ls config/private.config.toml && exit 1 || exit 0
        msg: config/private.config.toml already exists
    cmds:
      - '{{if eq OS "windows"}}
          copy config\\dev.config.toml config\\private.config.toml
        {{else}}
          cp config/dev.config.toml config/private.config.toml
        {{end}}'
      - echo Please go to config/private.config.toml and enter your Discord Bot credentials!
