_type: export
__export_format: 4
__export_date: 2022-05-05T21:29:59.380Z
__export_source: insomnia.desktop.app:v2022.3.0
resources:
  - _id: req_ff946c9566864922831a7233c174557b
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651596117723
    created: 1651242656771
    url: http://localhost:8080/api/v1/sounds
    name: list
    description: ""
    method: GET
    body: {}
    parameters:
      - id: pair_d03e7d6340cd43afb872a5a44a444bf8
        name: order
        value: name
        description: ""
        disabled: true
      - id: pair_36f3de20fb894443997006b2ab00bd5c
        name: include
        value: sexual
        description: ""
        disabled: true
      - id: pair_6a3ee58ea9dc4696b55141cfdb504e62
        name: exclude
        value: sexual
        description: ""
        disabled: true
    headers:
      - id: pair_4fd8de7cb9834303b38b6cef7cb01e53
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
    authentication: {}
    metaSortKey: -1651242656771
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: wrk_36eb46a5dd33494883580b6bf24413d6
    parentId: null
    modified: 1651242645974
    created: 1651242645974
    name: yuri69
    description: ""
    scope: collection
    _type: workspace
  - _id: req_61ee6182ea7c4735b8c57818b8ade754
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651244674961
    created: 1651244068849
    url: http://localhost:8080/api/v1/sounds/cum
    name: delete
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers:
      - id: pair_a1fa965946364c5cb55b632c8add0fc5
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
    authentication: {}
    metaSortKey: -1651242656746
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_b09458389240440ca7ff541ca969fdda
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651595823852
    created: 1651243649259
    url: http://localhost:8080/api/v1/sounds/upload
    name: upload
    description: ""
    method: PUT
    body:
      mimeType: multipart/form-data
      params:
        - id: pair_a6e52318c386418da52739054539f42a
          name: file
          value: ""
          description: ""
          type: file
          fileName: F:\dev\yuri69\data\sounds\insarschloch.mp3
        - id: pair_d0939a722a2f476ab6609e9aa3a59d9a
          name: ""
          value: ""
          description: ""
    parameters:
      - id: pair_16e9c98e65ae4271baa3dbda1f943411
        name: type
        value: audio/mp3
        description: ""
    headers:
      - id: pair_9f4ca43550484b1281efeb9d4d857bcf
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
      - name: Content-Type
        value: multipart/form-data
        id: pair_79eb0986190f4f5982f21b9144bbf471
    authentication: {}
    metaSortKey: -1651242656721
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_f487139ea12b4ee8be178ebc621c3e46
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651595841881
    created: 1651243704627
    url: http://localhost:8080/api/v1/sounds/create
    name: create
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"uid": "insarschloch",
        	"display_name": "",
        	"normalize": true,
        	"tags": ["sexual"],
        	"upload_id": "c9olkds774mjvi3fso5g"
        }
    parameters: []
    headers:
      - id: pair_cd8bb4ec416745978a97959dfc36283b
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
      - name: Content-Type
        value: application/json
        id: pair_496ff19b845a4f66b39608e9e4767101
    authentication: {}
    metaSortKey: -1651242656671
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_c2203d742dab43568c6e0dc862bbef62
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651785150151
    created: 1651785142158
    url: http://localhost:8080/api/v1/guilds/filters
    name: filters
    description: ""
    method: GET
    body: {}
    parameters:
      - id: pair_d03e7d6340cd43afb872a5a44a444bf8
        name: order
        value: name
        description: ""
        disabled: true
      - id: pair_36f3de20fb894443997006b2ab00bd5c
        name: include
        value: sexual
        description: ""
        disabled: true
      - id: pair_6a3ee58ea9dc4696b55141cfdb504e62
        name: exclude
        value: sexual
        description: ""
        disabled: true
    headers:
      - id: pair_4fd8de7cb9834303b38b6cef7cb01e53
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
    authentication: {}
    metaSortKey: -1651242656621
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_086cd22877ec454f974e6fc5304faeb0
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651785976129
    created: 1651785281532
    url: http://localhost:8080/api/v1/guilds/filters
    name: filters
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"include": ["pog", "Kek"],
        	"exclude": ["CHAMP"]
        }
    parameters:
      - id: pair_d03e7d6340cd43afb872a5a44a444bf8
        name: order
        value: name
        description: ""
        disabled: true
      - id: pair_36f3de20fb894443997006b2ab00bd5c
        name: include
        value: sexual
        description: ""
        disabled: true
      - id: pair_6a3ee58ea9dc4696b55141cfdb504e62
        name: exclude
        value: sexual
        description: ""
        disabled: true
    headers:
      - id: pair_4fd8de7cb9834303b38b6cef7cb01e53
        name: Authorization
        value: bearer
          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODI3NzkxMzksIm5iZiI6MTY1MTI0MzEzOSwiaWF0IjoxNjUxMjQzMTM5LCJVc2VySUQiOiIyMjE5MDU2NzEyOTYyNTM5NTMifQ.cWxMCyV8AMfsJYOsd0SGrIMXs8ABZOF5oQ4jydyZltI
        description: ""
      - name: Content-Type
        value: application/json
        id: pair_1676dc2c1718434a86dd56c58b9e5c40
    authentication: {}
    metaSortKey: -1649377778547.5
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_0dd3a98fd642fb5cfbbc5b093bb781d209c40120
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651242645984
    created: 1651242645984
    name: Base Environment
    data: {}
    dataPropertyOrder: null
    color: null
    isPrivate: false
    metaSortKey: 1651242645984
    _type: environment
  - _id: jar_0dd3a98fd642fb5cfbbc5b093bb781d209c40120
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651242645985
    created: 1651242645985
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_6a1cdfe32a094371a56f6443b691d6e4
    parentId: wrk_36eb46a5dd33494883580b6bf24413d6
    modified: 1651242645978
    created: 1651242645978
    fileName: yuri69
    contents: ""
    contentType: yaml
    _type: api_spec
