[Storage]
type = "file"

[Storage.File]
basepath = "data/st"

[Discord]
token = ""
ownerid = "221905671296253953"

[Webserver]
bindaddress = "localhost:8080"
publicaddress = "http://localhost:8080"

[Webserver.DiscordOAuth]
clientid = ""
clientsecret = ""

[Webserver.Auth]
refreshtokenkey = ""
accesstokenkey = ""
accesstokenlifetime = "10m"

[Lavalink]
address = "localhost:2333"
password = ""

[Player]
Hostname = "host.docker.internal"

[Database]
Type = "nuts"

[Database.Nuts]
Location = "data/db"
