[Storage]
type = "file"

[Storage.File]
basepath = "data/st"

[Storage.Minio]
endpoint = "example.com"
accesskeyid = "*****"
secretaccesskey = "*****"
location = "us-east-1"
secure = true

[Discord]
token = "*****"
ownerid = "221905671296253953"

[Webserver]
bindaddress = "localhost:8080"
publicaddress = "http://localhost:8080"

[Webserver.DiscordOAuth]
clientid = "*****"
clientsecret = "*****"

[Webserver.Auth]
refreshtokenkey = "*****"
accesstokenkey = "*****"
accesstokenlifetime = "10m"

[Player]
Hostname = "host.docker.internal"

[Player.Lavalink]
address = "localhost:2333"
password = "*****"

[Database]
Type = "nuts"

[Database.Nuts]
Location = "data/db"
