[Storage]
type = "file"

[Storage.File]
basepath = "data/st"

[Storage.Minio]
endpoint = "localhost:9000"
accesskeyid = "yuri69"
secretaccesskey = "yuri69_secret_key"
location = "us-east-1"
secure = false

[Discord]
token = ""
ownerid = ""

[Webserver]
bindaddress = "localhost:8080"
publicaddress = "http://localhost:8080"

[Webserver.DiscordOAuth]
clientid = ""
clientsecret = ""

[Webserver.Auth]
refreshtokenkey = "kekw"
refreshtokenlifetime = "8760h"
accesstokenkey = "kekw"

[Player]
Hostname = "host.docker.internal"

[Player.Lavalink]
address = "localhost:2333"
password = "password"

[Database]
Type = "nuts"

[Database.Nuts]
Location = "data/db"

[Database.Postgres]
Host = "localhost"
Port = 5432
Database = "yuri69"
Username = "yuri69"
Password = "yuri69"
